# Generated by Django 3.1.7 on 2021-03-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('rating', models.TextField(verbose_name='Rating')),
                ('track_list', models.TextField(verbose_name='List of tracks')),
                ('link_to_download', models.URLField(verbose_name='Link for download')),
                ('link_to_album', models.URLField(unique=True, verbose_name='Link to album on site')),
            ],
        ),
    ]
